Added variable amounts for movement and rotation
NextCenturyCorporation/ai2thor pull request #122
Opened 2021-03-29 12:43 UTC by erick-u

Added support for custom amounts to movement and rotation.

Movement actions will take 1 physics step per .1 movement. 
Rotation actions will take 1 physics step per 10 degrees.
Regardless of physics steps, each variable amount will result in 1 "action.

Example movement inputs: 
| Movement Amount  | Physics Steps | Actions |
| ------------- | ------------- | ------------- |
| 0.1  | 1  | 1  |
| 1  | 10  | 1  |

Example rotation inputs: 
| Rotation Amount  | Physics Steps | Actions |
| ------------- | ------------- | ------------- |
| 10  | 1  | 1  |
| 45  | 5  | 1  |

2021-03-29 17:58 UTC, ThomasSchellenbergNextCentury commented on unity/Assets/Scripts/MCSController.cs
> +        //Debug.LogWarning(rotationActionData.rotationChange);
Extra debug log statement.

2021-03-29 19:19 UTC, ThomasSchellenbergNextCentury commented on unity/Assets/Scripts/MCSController.cs
> +        var physicsSteps = 1;
Is there a reason why you're using `var` everywhere rather than `boolean`, `int`, etc.? Is that just a stylistic choice?

2021-03-29 20:30 UTC, erick-u commented on unity/Assets/Scripts/MCSController.cs
> +        var physicsSteps = 1;
It improves readability and is a styling choice but the code is already explicitly typed so I will update it to match this standard.

2021-03-29 20:30 UTC, erick-u commented on unity/Assets/Scripts/MCSController.cs
> +        //Debug.LogWarning(rotationActionData.rotationChange);
Will remove

2021-03-30 15:41 UTC, rartiss55 commented
Do we need to update DebugDiscreteAgentController as well? Was having trouble with using that method for the LookUp/LookDown actions.

2021-03-30 16:29 UTC, erick-u commented
@rartiss55 Ah, running through python will validate a default amount but using the DebugDiscreteAgentController directly does not offer any "default" values and will keep the values at 0. We can choose to update the DebugDiscreteAgentController or add some validation into the Look and Rotate functions if provided with no value. I believe adding it to the Look and Rotate functions may be preferred.

2021-03-30 17:47 UTC, rartiss55 commented
Either works, but I think it might be better in the DebugDiscreteAgentController from a maintenance perspective since we already have defaults in the Python API. By changing it in MCSController, if we need to update the default values in the Python API, we'd have to remember change it here too.

2021-04-19 13:40 UTC, ThomasSchellenbergNextCentury requested changes
@erick-u Unfortunately there's a big problem with this implementation right now. We need to update MCSController.step for the change in the number of steps, AND call MCSMain.Update on each intermediary step. See the example scene and actions posted below. In this scene, the performer moves 2.0 ahead, which should take 20 steps, and the force on the ball starts at step 10, which means that the force should start in the middle of the performer's movement. However, the force doesn't start until after the performer does 9 more actions, since the system is registering the `MoveAhead,movement=2.0` as 1 step and not 20.

Scene:

```json
{
    "name": "thomas_1",
    "version": 2,
    "ceilingMaterial": "AI2-THOR/Materials/Walls/Drywall",
    "floorMaterial": "AI2-THOR/Materials/Fabrics/CarpetWhite 3",
    "wallMaterial": "AI2-THOR/Materials/Walls/Drywall",
    "performerStart": {
        "position": {
            "x": 0,
            "z": 0
        },
        "rotation": {
            "x": 0,
            "y": 0
        }
    },
    "objects": [{
        "id": "testBall",
        "type": "ball",
        "mass": 1,
        "materials": ["AI2-THOR/Materials/Plastics/BlueRubber"],
        "salientMaterials": ["rubber"],
        "pickupable": true,
        "shows": [{
            "stepBegin": 0,
            "position": {
                "x": -3.281,
                "y": 0.125,
                "z": 1
            },
            "scale": {
                "x": 0.25,
                "y": 0.25,
                "z": 0.25
            }
        }],
        "forces": [{
            "stepBegin": 10,
            "stepEnd": 10,
            "vector": {
                "x": 700,
                "y": 0,
                "z": 0
            }
        }]
    }]
}
```

Actions:
- MoveAhead,movement=2.0

2022-12-15 19:06 UTC, closed without merging